version: '2'
services:
 wp:
  image: wordpress:4.7
  volumes:
   - ./themes:/var/www/html/wp-content/themes
  ports:
   - 80:80
  environment:
   - WORDPRESS_DB_PASSWORD=12432
   - WORDPRESS_DB_HOST=db 
 db:
  image: mysql:5.7
  environment:
   - MYSQL_ROOT_PASSWORD=12432
