version: '2'
services:
  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile.dev
    volumes:
      - "./landing/src:/app/src"
    ports:
      - "8080:8080"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - "./api/src:/app/src"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - "./web/src:/app/src"
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - api
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    volumes:
      - "./admin/src:/app/src"
    ports:
      - "8083:8083"
    depends_on:
      - mongo
      - api
  mongo:
    command: mongod
    image: mongo:3.2.0
    ports:
      - "27100:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none
